### ISSUE TITLE
neanderthal-no-op allowBackup

### ISSUE THREAD

**Issue by kamal-kamalmohamed** [outware/neanderthal#11]
The neanderthal-no-op module specifies in its AndroidManifest:

```
android:allowBackup="true"
```

This is undesired because it requires the utilising project to define:

```
tools:replace="android:allowBackup"
```

if it's setting the allowBackup attribute as false, eg:

```
<application
        android:allowBackup="false"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        tools:replace="android:allowBackup">
```

**Comment by timmutton** [comment]
attached to https://github.com/outware/neanderthal/pull/17

**Comment by kamal-kamalmohamed** [comment]
This issue is resolved.
