### ISSUE TITLE
Neanderthal requires extension of Application class

### ISSUE THREAD

**Issue by kamal-kamalmohamed** [outware/neanderthal#12]
Neanderthal requires extending the `Application` class. This is not ideal, and could probably be replaced by a more common initialisation by static method, eg.

```
Neanderthal.init(this);
```

that takes as a parameter the `Application` class itself.

**Comment by timmutton** [comment]
@kamal-kamalmohamed so I totally didnt see this, however I did fix this pretty much exactly how you asked

**Comment by kamal-kamalmohamed** [comment]
@timmutton: Yeah, I noticed. Good job. :P
