### ISSUE TITLE
Multiple Neanderthal instances on same device

### ISSUE THREAD

**Issue by kamal-kamalmohamed** [outware/neanderthal#18]
When we install multiple apps that use Neanderthal on the same device (not uncommon for a test device) it becomes really hard to distinguish between the multiple Neanderthal instances.

I'd propose to change Neanderthal's app name dynamically by suffixing the name of the app that we're configuring. 

Another option would be to allow for icon customisation from the host application.

**Comment by timmutton** [comment]
I dont believe we can set this dynamically, however you can override the name & icon by adding the following to your applications manifest:

<activity android:name="au.com.outware.neanderthal.presentation.view.activity.VariantListActivity"
            android:label={custom_neanderthal_name}
            android:icon={custom_neanderthal_icon}
            tools:replace="android:label, android:icon" />

alternatively, you can change the name by overriding the neanderthal_app_name string resource

**Comment by kamal-kamalmohamed** [comment]
I'm assuming this should be added to the application tag:

```
<application
        android:name=".SomeApplication"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        tools:replace="android:label, android:icon">
```

But if we were to apply both of them Neanderthal would have the same label and same icon as the main app, making them undistinguishable, right?

Overriding just the icon is a good enough workaround for the moment. I would keep the issue open to allow for customisation of Neanderthal name and icon independently from the app name and icon.

**Comment by timmutton** [comment]
sorry, my mistake. What you'll want to do is define an activity of the structure:

```
    <activity android:name="au.com.outware.neanderthal.presentation.view.activity.VariantListActivity"
            android:label="{label}"
            android:icon="{icon}"
            android:taskAffinity="{bundle_id}.neanderthal"
            tools:replace="android:label,android:icon,android:taskAffinity" />
```

**Comment by kamal-kamalmohamed** [comment]
That makes more sense! OK then, it works. It should just be documented somewhere.
